import axios from "axios";

export const ERROR_CODES = {
  INVALID_EMAIL_VERIFICATION_CODE: "INVALID_EMAIL_VERIFICATION_CODE",
  CONCURRENT_EMAIL_VERIFICATION: "CONCURRENT_EMAIL_VERIFICATION",
  DISCRIMINATOR_CONFLICT: "DISCRIMINATOR_CONFLICT",
  OAUTH_EMAIL_CONFLICT: "OAUTH_EMAIL_CONFLICT",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  INVALID_OAUTH_STATE: "INVALID_OAUTH_STATE",
  INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_SESSION: "INVALID_SESSION",
  INVALID_TOKEN: "INVALID_TOKEN",
} as const;

export type ApiErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const httpClient = axios.create({
  baseURL: import.meta.env.VITE_API_URL ?? "http://localhost:3000",
  headers: { "Content-Type": "application/json" },
  withCredentials: true,
});
