import { INSTANCE_CONSTANT } from "@/features/instances/constants/instance.constant";
import { AUTH_CONSTANT } from "@/features/auth/constants/auth.constant";

export const APP_PATH = {
  HOME: "/",

  AUTH: {
    LAYOUT: `/${AUTH_CONSTANT.ROUTER.LAYOUT}`,
    SIGN_IN: `/${AUTH_CONSTANT.ROUTER.LAYOUT}/${AUTH_CONSTANT.ROUTER.SIGN_IN}`,
    SIGN_UP: `/${AUTH_CONSTANT.ROUTER.LAYOUT}/${AUTH_CONSTANT.ROUTER.SIGN_UP}`,
    EMAIL_VERIFICATION: `/${AUTH_CONSTANT.ROUTER.LAYOUT}/${AUTH_CONSTANT.ROUTER.EMAIL_VERIFICATION}`,
    RESET_PASSWORD: `/${AUTH_CONSTANT.ROUTER.LAYOUT}/${AUTH_CONSTANT.ROUTER.RESET_PASSWORD}`,
    OAUTH_CALLBACK: `/${AUTH_CONSTANT.ROUTER.LAYOUT}/${AUTH_CONSTANT.ROUTER.OAUTH_CALLBACK}`
  },

  INSTANCES: `/${INSTANCE_CONSTANT.ROUTER.INSTANCES}`,
  INSTANCE: `/${INSTANCE_CONSTANT.ROUTER.INSTANCE}/:ID`,
} as const;
