import { APP_CONSTANT } from "./app.constant";

export const APP_PATH = {
  HOME: "/",

  AUTH: {
    LAYOUT: `/${APP_CONSTANT.ROUTER.AUTH.LAYOUT}`,
    SIGN_IN: `/${APP_CONSTANT.ROUTER.AUTH.LAYOUT}/${APP_CONSTANT.ROUTER.AUTH.SIGN_IN}`,
    SIGN_UP: `/${APP_CONSTANT.ROUTER.AUTH.LAYOUT}/${APP_CONSTANT.ROUTER.AUTH.SIGN_UP}`,
    EMAIL_VERIFICATION: `/${APP_CONSTANT.ROUTER.AUTH.LAYOUT}/${APP_CONSTANT.ROUTER.AUTH.EMAIL_VERIFICATION}`,
    RESET_PASSWORD: `/${APP_CONSTANT.ROUTER.AUTH.LAYOUT}/${APP_CONSTANT.ROUTER.AUTH.RESET_PASSWORD}`,
  },

  INSTANCES: `/${APP_CONSTANT.ROUTER.INSTANCES.INSTANCES}`,
  INSTANCE: `/${APP_CONSTANT.ROUTER.INSTANCES.INSTANCE}/:ID`,
} as const;
